# cloudbuild.yaml — Build from Dockerfile and deploy to Cloud Run

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _REGION: us-west2
  _SERVICE: los-emos-karaoke
  _AR_PATH: us-west2-docker.pkg.dev/steady-petal-471617-c1/cloud-run-source-deploy/los-emos/los-emos-karaoke

steps:
  # 1) Build container image from Dockerfile
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - ${_AR_PATH}:$SHORT_SHA
      - -f
      - Dockerfile
      - .

  # 2) Push image to Artifact Registry
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - ${_AR_PATH}:$SHORT_SHA

  # 3) Deploy to Cloud Run
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ${_SERVICE}
      - --image=${_AR_PATH}:$SHORT_SHA
      - --region=${_REGION}
      - --platform=managed
      - --allow-unauthenticated

images:
  - ${_AR_PATH}:$SHORT_SHA
